connect:
    - key: "lab"
      fullname: "实验室"
      icon: "fa-solid fa-flask"
      link: "https://seen.moe/lab"
    - key: "daily"
      fullname: "日常"
      icon: "fa-solid fa-swatchbook"
      link: "https://daily.seen.moe"
    - key: "tech"
      fullname: "技术"
      icon: "fa-solid fa-code-compare"
      link: "https://tech.seen.moe"
