profileInfo:
    intro: "川崎雫，来自中国的高一学生，无所事事的一般人。"
    bio: "追逐流逝的烟火，我的世界空无一物。"
    description: "业余开发者，业余摄影爱好者，业余写手，业余视频制作，反正总而言之就是业余的就对了，技能点很泛，没什么专精的但什么都会，学习速度很快。被心情支配的工具人罢了，偶尔还是有点正常的情感和奇思妙想。"
    avatar: "https://seen-1302639736.file.myqcloud.com/site-data/homepage/avatar01.webp"
