social:
    - key: "github"
      fullname: "GitHub"
      icon: "fa-brands fa-github"
      hover: "hover:bg-[#24292e]"
      link: "https://github.com/ifshizuku"
      hot: "true"
    - key: "twitter"
      fullname: "Twitter"
      icon: "fa-brands fa-twitter"
      hover: "hover:bg-[#1da1f2]"
      link: "https://twitter.com/ifshizuku"
    - key: "telegram"
      fullname: "Telegram"
      icon: "fa-brands fa-telegram"
      hover: "hover:bg-[#0088cc]"
      link: "https://t.me/ifshizuku"
      hot: "true"
    - key: "line"
      fullname: "Line"
      icon: "fa-brands fa-line"
      hover: "hover:bg-[#00c300]"
      link: "https://line.me/ti/p/hiN7E4l3c-"
    - key: "dribbble"
      fullname: "Dribbble"
      icon: "fa-brands fa-dribbble"
      hover: "hover:bg-[#ea4c89]"
      link: "https://dribbble.com/ifshizuku"
    - key: "bilibili"
      fullname: "Bilibili"
      icon: "fa-brands fa-bilibili"
      hover: "hover:bg-[#f9a8d4]"
      link: "https://space.bilibili.com/365243793"
      hot: "true"
    - key: "unsplash"
      fullname: "Unsplash"
      icon: "fa-brands fa-unsplash"
      hover: "hover:bg-[#24292e]"
      link: "https://unsplash.com/@ifshizuku"
    - key: "qq"
      fullname: "QQ"
      icon: "fa-brands fa-qq"
      hover: "hover:bg-[#7dd3fc]"
      link: "http://wpa.qq.com/msgrd?v=3&uin=2419155436&site=qq&menu=yes"
      hot: "true"
    - key: "mail"
      fullname: "邮箱"
      icon: "fa-solid fa-envelope"
      hover: "hover:bg-[#5eead4]"
      link: "mailto:starsmoe@outlook.com"
    - key: "ncm"
      fullname: "网易云音乐"
      icon: "iconfont icon-netease-cloud-music-line"
      hover: "hover:bg-[#f87171]"
      link: "https://music.163.com/#/user/home?id=1819287517"
      hot: "true"
    - key: "coolapk"
      fullname: "酷安"
      icon: "iconfont icon-coolapk"
      hover: "hover:bg-[#4ade80]"
      link: "http://www.coolapk.com/u/2491326"
      hot: "true"
    - key: "lofter"
      fullname: "LOFTER"
      icon: "iconfont icon-LOFTER"
      hover: "hover:bg-[#0f766e]"
      link: "https://ifshizuku.lofter.com"
    - key: "xhs"
      fullname: "小红书"
      icon: "iconfont icon-xiaohongshuicon"
      hover: "hover:bg-[#f43f5e]"
      link: "https://www.xiaohongshu.com/user/profile/61f7bc9e000000001000faa2"
    - key: "figma"
      fullname: "Figma"
      icon: "fa-brands fa-figma"
      hover: "hover:bg-[#f87171]"
      link: "https://www.figma.com/@shizuku"
    - key: "zhihu"
      fullname: "知乎"
      icon: "iconfont icon-zhihu"
      hover: "hover:bg-[#3b82f6]"
      link: "https://www.zhihu.com/people/coldwith"
      hot: "true"
