meta:
    siteTitle: "旧念 / Seen"
    siteAuthor: "Kawasaki Shizuku"
    siteDescription: "川崎雫的个人导航站点，从过去走来，连接新的开始。旧念，只为昔见。15岁高中生，什么都会一点但什么都不专精的废柴。点子很多，但是没有什么特别的。被心情支配的工具人，开发方向集中在 Web 前端，自学了界面设计以及不少专业技能。除了一直都很累之外。x):"
    og:
        image: "https://seen-1302639736.file.myqcloud.com/site-data/homepage/favicon/si.webp"
        title: "Seen 导航页，从这里开始连接"
        description: "这里是川崎雫的个人站点。一个什么都会但什么都不专精的废柴。欢迎来到我的世界，我会一直都在这里。"
        locale: "zh_CN"
        siteName: "旧念 / Seen"
    tw:
        image: "https://seen.moe/icons/android-chrome-192x192.png"
        title: "Seen 导航页，从这里开始连接"
        card: "旧念 / Seen"
        link: "https://seen.moe"
        description: "这里是川崎雫的个人站点。一个什么都会但什么都不专精的废柴。欢迎来到我的世界，我会一直都在这里。"
        creator: "Kawasaki Shizuku"
    pwa:
        name: "Seen"
        appleMobileWebAppTitle: "Seen"

headedView:
    backgroundImage: "https://seen-1302639736.file.myqcloud.com/site-data/homepage/bg-05.webp"
    i:
        info: "Seen"
    ds:
        sentence: "Kawasaki Shizuku / Rainy Umbrella"
        moreicon:
            series: "solid"
            icon: "fa-arrow-down-short-wide"

secondaryView:
    profileInfo:
        intro: "川崎雫，来自中国的高一学生，无所事事的一般人。"
        bio: "追逐流逝的烟火，我的世界空无一物。"
        description: "业余开发者，业余摄影爱好者，业余写手，业余视频制作，反正总而言之就是业余的就对了，技能点很泛，没什么专精的但什么都会，学习速度很快。被心情支配的工具人罢了，偶尔还是有点正常的情感和奇思妙想。"
        avatar: "https://seen-1302639736.file.myqcloud.com/site-data/homepage/avatar01.webp"
    skills:
        - key: "js"
          fullname: "Javascript"
          faicon: "fa-brands fa-js-square"
          brandColor: "#eed94d"
          hover: "hover:bg-yellow-300"
          progress: 60%
        - key: "react"
          fullname: "React JS"
          faicon: "fa-brands fa-react"
          brandColor: "#61dafb"
          hover: "hover:bg-sky-400"
          progress: 40%
        - key: "swift"
          fullname: "Swift"
          faicon: "fa-brands fa-swift"
          brandColor: "#f87171"
          hover: "hover:bg-orange-400"
          progress: 15%
        - key: "sketch"
          fullname: "Sketch"
          faicon: "fa-brands fa-sketch"
          brandColor: "#f4d35e"
          hover: "hover:bg-yellow-400"
          progress: 85%
        - key: "design"
          fullname: "设计"
          faicon: "fa-solid fa-paint-brush"
          brandColor: "#7dd3fc"
          hover: "hover:bg-blue-400"
          progress: 60%
          refix: true
        - key: "photography"
          fullname: "摄影"
          faicon: "fa-solid fa-camera"
          brandColor: "#fda4af"
          hover: "hover:bg-rose-400"
          progress: 45%
          refix: true
        - key: "video"
          fullname: "视频制作"
          faicon: "fa-solid fa-video"
          brandColor: "#c4b5fd"
          hover: "hover:bg-violet-400"
          progress: 40%
          refix: true
        - key: "writing"
          fullname: "写作"
          faicon: "fa-solid fa-feather-pointed"
          brandColor: "#86efac"
          hover: "hover:bg-lime-400"
          progress: 50%
          refix: true
        - key: "guitar"
          fullname: "吉他"
          faicon: "fa-solid fa-guitar"
          brandColor: "#f9a8d4"
          hover: "hover:bg-pink-400"
          progress: 85%
          refix: true

    social:
        - key: "github"
          fullname: "GitHub"
          icon: "fa-brands fa-github"
          hover: "hover:bg-[#24292e]"
          link: "https://github.com/ifshizuku"
          hot: "true"
        - key: "twitter"
          fullname: "Twitter"
          icon: "fa-brands fa-twitter"
          hover: "hover:bg-[#1da1f2]"
          link: "https://twitter.com/ifshizuku"
        - key: "telegram"
          fullname: "Telegram"
          icon: "fa-brands fa-telegram"
          hover: "hover:bg-[#0088cc]"
          link: "https://t.me/ifshizuku"
          hot: "true"
        - key: "line"
          fullname: "Line"
          icon: "fa-brands fa-line"
          hover: "hover:bg-[#00c300]"
          link: "https://line.me/ti/p/hiN7E4l3c-"
        - key: "dribbble"
          fullname: "Dribbble"
          icon: "fa-brands fa-dribbble"
          hover: "hover:bg-[#ea4c89]"
          link: "https://dribbble.com/ifshizuku"
        - key: "bilibili"
          fullname: "Bilibili"
          icon: "fa-brands fa-bilibili"
          hover: "hover:bg-[#f9a8d4]"
          link: "https://space.bilibili.com/365243793"
          hot: "true"
        - key: "unsplash"
          fullname: "Unsplash"
          icon: "fa-brands fa-unsplash"
          hover: "hover:bg-[#24292e]"
          link: "https://unsplash.com/@ifshizuku"
        - key: "qq"
          fullname: "QQ"
          icon: "fa-brands fa-qq"
          hover: "hover:bg-[#7dd3fc]"
          link: "http://wpa.qq.com/msgrd?v=3&uin=2419155436&site=qq&menu=yes"
          hot: "true"
        - key: "mail"
          fullname: "邮箱"
          icon: "fa-solid fa-envelope"
          hover: "hover:bg-[#5eead4]"
          link: "mailto:starsmoe@outlook.com"
        - key: "ncm"
          fullname: "网易云音乐"
          icon: "iconfont icon-netease-cloud-music-line"
          hover: "hover:bg-[#f87171]"
          link: "https://music.163.com/#/user/home?id=1819287517"
          hot: "true"
        - key: "coolapk"
          fullname: "酷安"
          icon: "iconfont icon-coolapk"
          hover: "hover:bg-[#4ade80]"
          link: "http://www.coolapk.com/u/2491326"
          hot: "true"
        - key: "lofter"
          fullname: "LOFTER"
          icon: "iconfont icon-LOFTER"
          hover: "hover:bg-[#0f766e]"
          link: "https://ifshizuku.lofter.com"
        - key: "xhs"
          fullname: "小红书"
          icon: "iconfont icon-xiaohongshuicon"
          hover: "hover:bg-[#f43f5e]"
          link: "https://www.xiaohongshu.com/user/profile/61f7bc9e000000001000faa2"
        - key: "figma"
          fullname: "Figma"
          icon: "fa-brands fa-figma"
          hover: "hover:bg-[#f87171]"
          link: "https://www.figma.com/@shizuku"
        - key: "zhihu"
          fullname: "知乎"
          icon: "iconfont icon-zhihu"
          hover: "hover:bg-[#3b82f6]"
          link: "https://www.zhihu.com/people/coldwith"
          hot: "true"
