# Site Meta Data
meta:
    title: "旧念 / Seen"
    description: "川崎雫的个人导航站点，从过去走来，连接新的开始。旧念，只为昔见。15岁高中生，什么都会一点但什么都不专精的废柴。点子很多，但是没有什么特别的。被心情支配的工具人，开发方向集中在 Web 前端，自学了界面设计以及不少专业技能。除了一直都很累之外。x):"
    keywords: "homepage, index, seen, Seen, 旧念, 川崎雫, Kawasaki Shizuku, Shizuku, Kawasaki, 雫, 个人站点, 博客, blog, personal site"
    url: "https://seen.moe"

# Site Navigation
nav:
    title: "Seen"
    subtitle: "本站建设中...差多了"
    sign: "下雨的伞"
    menu:
        - name: "实验室"
          url: "https://seen.moe/lab"
          key: "lab"
        - name: "记录"
          url: "https://seen.moe/record"
          key: "record"

# Profile
profile:
    intro: "川崎雫，来自中国的高一学生，无所事事的一般人。"
    bioOne: "Forever / FORNEVER 。"
    bioTwo: "追逐流逝的烟火，我的世界空无一物。"
    description: "业余开发者，业余摄影爱好者，业余写手，业余视频制作，反正总而言之就是业余的就对了，技能点很泛，没什么专精的但什么都会，学习速度很快。被心情支配的工具人罢了，偶尔还是有点正常的情感和奇思妙想，或许。"

# Footer
footer:
    text: "Copyright © Kawasaki Shizuku"
    icp:
        text: "萌ICP备"
        textLink: "https://icp.gov.moe"
        number: "20210003 号"
        numberLink: "https://icp.gov.moe/?keyword=20210003"

# Social
social:
    - id: "card-github"
      key: "gh"
      fullname: "Github"
      icon:
          series: brands
          name: github-alt
      brandColor: "#24292e"
      hoverController: ghhover
      link: "https://github.com/ifshizuku"
    - id: "card-twitter"
      key: "tw"
      fullname: "Twitter"
      icon:
          series: brands
          name: twitter
      brandColor: "#1da1f2"
      hoverController: twhover
      link: "https://twitter.com/ifshizuku"
    - id: "card-bilibili"
      key: "bili"
      fullname: "Bilibili"
      icon:
          series: brands
          name: bilibili
      brandColor: "#38bdf8"
      hoverController: bilihover
      link: "https://space.bilibili.com/365243793"
    - id: "card-telegram"
      key: "telegram"
      fullname: "Telegram"
      icon:
          series: brands
          name: telegram
      brandColor: "#0088cc"
      hoverController: telegramhover
      link: "https://t.me/ifshizuku"
    - id: "card-mail"
      key: "mail"
      fullname: "Mail"
      icon:
          series: solid
          name: envelope
      brandColor: "#f9a8d4"
      hoverController: mailhover
      link: "mailto:starsmoe@outlook.com"
    - id: "card-qq"
      key: "qq"
      fullname: "QQ"
      icon:
          series: brands
          name: qq
      brandColor: "#7c7c7c"
      hoverController: qqhover
      link: "http://wpa.qq.com/msgrd?v=3&uin=2419155436&site=qq&menu=yes"

# Skills
skills:
    - id: card-js
      key: js
      fullname: JavaScript
      icon:
          series: brands
          name: js-square
      brandColor: '#eed94d'
      hover: 'hover:bg-yellow-300'
      hoverController: jshover
      process: w-3/4
    - id: card-react
      key: react
      fullname: React JS
      icon:
          series: brands
          name: react
      brandColor: '#61dafb'
      hover: 'hover:bg-sky-400'
      hoverController: reacthover
      process: w-1/2
    - id: card-swift
      key: swift
      fullname: Swift
      icon:
          series: brands
          name: swift
      brandColor: '#f87171'
      hover: 'hover:bg-orange-400'
      hoverController: swifthover
      process: w-1/4
    - id: card-sketch
      key: sketch
      fullname: Sketch
      icon:
          series: brands
          name: sketch
      brandColor: '#fbbf24'
      hover: 'hover:bg-yellow-400'
      hoverController: sketchhover
      process: w-5/6
    - id: card-design
      key: design
      fullname: 界面设计
      icon:
          series: solid
          name: compass-drafting
      brandColor: '#7dd3fc'
      hover: 'hover:bg-blue-400'
      hoverController: designhover
      process: w-3/4
    - id: card-video
      key: video
      fullname: 视频制作
      icon:
          series: solid
          name: film
      brandColor: '#c4b5fd'
      hover: 'hover:bg-violet-400'
      hoverController: videohover
      process: w-1/2
    - id: card-writing
      key: writing
      fullname: 写作
      icon:
          series: solid
          name: feather-pointed
      brandColor: '#86efac'
      hover: 'hover:bg-lime-400'
      hoverController: writinghover
      process: w-1/2
    - id: card-photography
      key: photography
      fullname: 摄影
      icon:
          series: solid
          name: camera
      brandColor: '#fda4af'
      hover: 'hover:bg-rose-400'
      hoverController: photographyhover
      process: w-1/2
    - id: card-paint
      key: paint
      fullname: 绘画
      icon:
          series: solid
          name: paint-brush
      brandColor: '#93c5fd'
      hover: 'hover:bg-indigo-400'
      hoverController: painthover
      process: w-1/4
    - id: card-guitar
      key: guitar
      fullname: 吉他
      icon:
          series: solid
          name: guitar
      brandColor: '#f9a8d4'
      hover: 'hover:bg-pink-400'
      hoverController: guitarhover
      process: w-3/4